const TABELAS = {
  MC_CAD_PRODUTO: {
    tableName: 'MC_CAD_PRODUTO',
    archiveName: '1 - MC_CAD_PRODUTO',
    dependencyLevel: 3,
  },
  MC_CAD_FOCO_NEGOCIO: {
    tableName: 'MC_CAD_FOCO_NEGOCIO',
    archiveName: '2 - MC_CAD_FOCO_NEGOCIO',
    dependencyLevel: 2,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idFocoNegocio',
  },
  MC_CAD_SEGMENTO_TARIFADOR: {
    tableName: 'MC_CAD_SEGMENTO_TARIFADOR',
    archiveName: '3 - MC_CAD_SEGMENTO_TARIFADOR',
    dependencyLevel: 1,
    archiveReference: '2 - MC_CAD_FOCO_NEGOCIO',
    referenceColumn: 'idSegmentoTarifador',
  },
  MC_CAD_GRUPO_PRODUTO: {
    tableName: 'MC_CAD_GRUPO_PRODUTO',
    archiveName: '4 - MC_CAD_GRUPO_PRODUTO',
    dependencyLevel: 2,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idTipoRecebimento',
  },
  MC_CAD_GRUPO_PRODUTO_RISCO: {
    tableName: 'MC_CAD_GRUPO_PRODUTO_RISCO',
    archiveName: '5 - MC_CAD_GRUPO_PRODUTO_RISCO',
    dependencyLevel: 1,
    archiveReference: '4 - MC_CAD_GRUPO_PRODUTO',
    referenceColumn: 'idGrupoProdutoRisco',
  },
  MC_CAD_CLASSIFICACAO_PRODUTO: {
    tableName: 'MC_CAD_CLASSIFICACAO_PRODUTO',
    archiveName: '6 - MC_CAD_CLASSIFICACAO_PRODUTO',
    dependencyLevel: 1,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idClassificacaoProduto',
  },
  MC_CAD_TIPO_PRODUTO: {
    tableName: 'MC_CAD_TIPO_PRODUTO',
    archiveName: '6 - MC_CAD_TIPO_PRODUTO',
    dependencyLevel: 1,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idTipoProduto',
  },
  MC_CAD_SUBPRODUTO: {
    tableName: 'MC_CAD_SUBPRODUTO',
    archiveName: '7 - MC_CAD_SUBPRODUTO',
    dependencyLevel: 1,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idSubproduto',
  },
  MC_CAD_PRODUTO_INDEXADOR: {
    tableName: 'MC_CAD_PRODUTO_INDEXADOR',
    archiveName: '8 - MC_CAD_PRODUTO_INDEXADOR',
    dependencyLevel: 1,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idIndexador',
  },
  MC_CAD_PRODUTO_TP_RECEBIMENTO: {
    tableName: 'MC_CAD_PRODUTO_TP_RECEBIMENTO',
    archiveName: '9 - MC_CAD_PRODUTO_TP_RECEBIMENTO',
    dependencyLevel: 1,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idTipoRecebimento',
  },
  MC_CAD_PRODUTO_KIT: {
    tableName: 'MC_CAD_PRODUTO_KIT',
    archiveName: '10 - MC_CAD_PRODUTO_KIT',
    dependencyLevel: 1,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'id',
    whereColumn: 'idProduto',
  },/**
  MC_CAD_PRODUTO_TP_RECEBIMENTO: {
    tableName: 'MC_CAD_PRODUTO_TP_RECEBIMENTO',
    archiveName: '2 - MC_CAD_PRODUTO_TP_RECEBIMENTO',
    dependencyLevel: 1,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idTipoRecebimento',
  },
  MC_CAD_PRODUTO_TP_RECEBIMENTO: {
    tableName: 'MC_CAD_PRODUTO_TP_RECEBIMENTO',
    archiveName: '2 - MC_CAD_PRODUTO_TP_RECEBIMENTO',
    dependencyLevel: 1,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idTipoRecebimento',
  },
  MC_CAD_PRODUTO_TP_RECEBIMENTO: {
    tableName: 'MC_CAD_PRODUTO_TP_RECEBIMENTO',
    archiveName: '2 - MC_CAD_PRODUTO_TP_RECEBIMENTO',
    dependencyLevel: 1,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idTipoRecebimento',
  },
  MC_CAD_PRODUTO_TP_RECEBIMENTO: {
    tableName: 'MC_CAD_PRODUTO_TP_RECEBIMENTO',
    archiveName: '2 - MC_CAD_PRODUTO_TP_RECEBIMENTO',
    dependencyLevel: 1,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idTipoRecebimento',
  },
  MC_CAD_PRODUTO_TP_RECEBIMENTO: {
    tableName: 'MC_CAD_PRODUTO_TP_RECEBIMENTO',
    archiveName: '2 - MC_CAD_PRODUTO_TP_RECEBIMENTO',
    dependencyLevel: 1,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idTipoRecebimento',
  },
  MC_CAD_PRODUTO_TP_RECEBIMENTO: {
    tableName: 'MC_CAD_PRODUTO_TP_RECEBIMENTO',
    archiveName: '2 - MC_CAD_PRODUTO_TP_RECEBIMENTO',
    dependencyLevel: 1,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idTipoRecebimento',
  },
  MC_CAD_PRODUTO_TP_RECEBIMENTO: {
    tableName: 'MC_CAD_PRODUTO_TP_RECEBIMENTO',
    archiveName: '2 - MC_CAD_PRODUTO_TP_RECEBIMENTO',
    dependencyLevel: 1,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idTipoRecebimento',
  },
  MC_CAD_PRODUTO_TP_RECEBIMENTO: {
    tableName: 'MC_CAD_PRODUTO_TP_RECEBIMENTO',
    archiveName: '2 - MC_CAD_PRODUTO_TP_RECEBIMENTO',
    dependencyLevel: 1,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idTipoRecebimento',
  },
  MC_CAD_PRODUTO_TP_RECEBIMENTO: {
    tableName: 'MC_CAD_PRODUTO_TP_RECEBIMENTO',
    archiveName: '2 - MC_CAD_PRODUTO_TP_RECEBIMENTO',
    dependencyLevel: 1,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idTipoRecebimento',
  },
  MC_CAD_PRODUTO_TP_RECEBIMENTO: {
    tableName: 'MC_CAD_PRODUTO_TP_RECEBIMENTO',
    archiveName: '2 - MC_CAD_PRODUTO_TP_RECEBIMENTO',
    dependencyLevel: 1,
    archiveReference: '1 - MC_CAD_PRODUTO',
    referenceColumn: 'idTipoRecebimento',
  }, */
};

module.exports = TABELAS;